### ISSUE TITLE
problem with prebuilts apks

### ISSUE THREAD

**Issue by meloalfa159** [Kenvyra/android_external_GmsCompatConfig#1]
hi firends, i'm build kenvyra for mi 11 lite 4g and i'm facing troubles with verify uses-libraries:

`Verifying uses-libraries: external/GmsCompatConfig/prebuilt/GmsCo
FAILED: out/target/common/obj/APPS/GmsCompatConfig_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/GmsCompatConfig_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	 
 --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/com
mon/obj/APPS/GmsCompatConfig_intermediates/enforce_uses_libraries.status 	 
 --aapt out/host/linux-x86/bin/aapt 	   	   	   	   	  external/GmsCompatConfig/prebuilt/GmsCompatConfig.apk )"
error: Command '['out/host/linux-x86/bin/aapt', 'dump', 'badging', 'external/Gms
CompatConfig/prebuilt/GmsCompatConfig.apk']' returned non-zero exit status -4`

hope you answer with a possible fix, thank you

**Comment by Tomoms** [comment]
Hi @meloalfa159  , you most likely have old(ish) CPUs in your computer, right? The fix is to apply this patch to your zlib: https://github.com/Tomoms/android_external_zlib-ng/commit/b20fe23575d065e23dfcb84834d8a1af089d071a

**Comment by meloalfa159** [comment]
> Hi @meloalfa159 , you most likely have old(ish) CPUs in your computer, right? The fix is to apply this patch to your zlib: [Tomoms/android_external_zlib-ng@b20fe23](https://github.com/Tomoms/android_external_zlib-ng/commit/b20fe23575d065e23dfcb84834d8a1af089d071a)

thank you for the answer. yes, i have a super old FX-8350 but it do his job and for me is okay. i will follow your advice, thank you!
